server:
   port: 9090
   
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka/

# Micrometer
management:
  metrics:
    export:
      prometheus:
        enabled: true

# Zipkin
spring:
  zipkin:
    base-url: http://zipkin-server:9411

