server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Micrometer
management:
  metrics:
    export:
      prometheus:
        enabled: true

# Zipkin
spring:
  zipkin:
    base-url: http://zipkin-server:9411

datasource:
  url: jdbc:mysql://localhost:3306/employee_management_system?useSSL=false
  username: root
  password: Thakur@1995$
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
