server:
   port: 8082
   
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka/

# Micrometer
management:
  metrics:
    export:
      prometheus:
        enabled: true

# Zipkin
spring:
  zipkin:
    base-url: http://zipkin-server:9411


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system?useSSL=false
    username: root
    password: Thakur@1995$

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
